# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['xjlagent.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'base64',
        'ctypes',
        'difflib',
        'http.server',
        'io',
        'json',
        'openpyxl',
        'pathlib',
        'prompt_toolkit',
        'prompt_toolkit.completion',
        'prompt_toolkit.formatted_text',
        'requests',
        'rich',
        'rich.box',
        'rich.console',
        'rich.live',
        'rich.markdown',
        'rich.panel',
        'sqlite3',
        'tarfile',
        'urllib.parse',
        'urllib.request',
        'webbrowser',
        'xml.etree.ElementTree',
        'zipfile',
        'fitz',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['tkinter', 'matplotlib'],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='xjlagent',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
